---
title: "Presentations"
---

# Oral Presentations

(\* indicates presenter)

1.  **Rodgers-Melnick SN\***, Bradt J, Dusek JA (Oct 2023). Music Therapy for Chronic Pain: Practical Recommendations for Future Research. American Music Therapy Association Symposium, Virtual
2.  **Rodgers-Melnick SN\*** (Aug 2023). The Role of Music Therapy in Sickle Cell Disease. Sickle Cell Data Collection Program California, Virtual
3.  Vroom D\*, **Rodgers-Melnick SN**, Brown T, Owusu-Ansah A, Dusek JA (Jun 2023). Pain Screening in Sickle Cell Youth (PASSKEY). Foundation For Sickle Cell Disease Research's 17th Annual Sickle Cell Disease Research and Educational Symposium and 46th National Sickle Cell Disease Scientific Meeting, Fort Lauderdale, FL
4.  Owusu-Ansah A\*, **Rodgers-Melnick SN\*** (May 2023). Pain Screening in Sickle Cell Youth (PASSKEY). University Hospitals Rainbow Babies & Children’s Hospital Pediatric Hematology Oncology Division Meeting, Cleveland, OH
5.  **Rodgers-Melnick SN\*** (Mar 2023). Melody of Healing: The Magic of Music Therapy on the Quality of Life in Adults with Sickle Cell Disease. International Association of Sickle Cell Nurses and Professional Associates (IASCNAPA) Virtual 2023 Conference
6.  **Rodgers-Melnick SN\***, Hansen KA\*, Dusek JA (Mar 2023). Data for Whole Health: Importance, Process, and Outcomes. Integrative Medicine & Health Symposium, Chicago, IL
7.  **Rodgers-Melnick SN\*** (Nov 2022). The Role of Music Therapy in Sickle Cell Disease. Chi Eta Phi Sorority, Incorporated Virtual Education Webinar, Virtual
8.  **Rodgers-Melnick SN\***, Block S, Rivard RL, Dusek JA (Oct 2022). Delivery and Effectiveness of Music Therapy in Hematology and Oncology: A Retrospective Study. Society for Integrative Oncology International Conference, Scottsdale, AZ
9.  **Rodgers-Melnick SN\*** (Sep 2022). Effectiveness of Medical Music Therapy Practice: Integrative Research Using the Electronic Health Record. Bravenet Practice-Based Research Network, Virtual
10. Dusek JA\**,* **Rodgers-Melnick SN\*** (Aug 2022). Data for Whole Health: Importance, Process, and Outcomes. University Hospitals Connor Whole Health Retreat, Cleveland, OH
11. **Rodgers-Melnick SN**, Bartolovich M, Miller DW, Dusek JA, Brown T\*, Owusu-Ansah A (Jun 2022). Massage Therapy for Youth with Sickle Cell Disease: A Retrospective Study. Foundation For Sickle Cell Disease Research's 16th Annual Sickle Cell Disease Research and Educational Symposium and 45th National Sickle Cell Disease Scientific Meeting, Fort Lauderdale, FL
12. **Rodgers-Melnick SN\****,* Robb SL\*, Bair JM\**,* Story K\*, Lane D\* (Jun 2022). When Music Relieves Pain and Suffering (Panel). Sound Health Network Inaugural Convening: Music Heals: How Music Improves Mental Well-Being, San Francisco, CA
13. Dusek JA\*, **Rodgers-Melnick SN**, Rivard RL, Adan F (May 2022). A Retrospective Pilot Study of Patient Reported Outcomes Collection in Outpatient Integrative Medicine Clinics. International Congress on Integrative Medicine and Health, Phoenix, AZ
14. **Rodgers-Melnick SN\***, Block S, Rivard RL, Dusek JA (May 2022). Effectiveness of Medical Music Therapy Practice: Integrative Research Using the Electronic Health Record (EMMPIRE): A Retrospective Study. International Congress on Integrative Medicine and Health, Phoenix, AZ
15. **Rodgers-Melnick SN\****,* McKee K\*, Edwards J\* (Mar 2022). Music Therapy in the Management of Sickle Cell Disease and other Painful Conditions. Sound Health Network, Virtual
16. Rao S\**,* Walker DA\*, **Rodgers-Melnick SN\****,* Bullock E\* (Mar 2022). Demystifying Integrative Oncology. GRYT Health, Virtual
17. **Rodgers-Melnick SN\*** (Oct 2021). Music Therapy in Comprehensive Cancer Care. Case Western Reserve University School of Medicine, Cleveland, OH
18. **Rodgers-Melnick SN\****,* McKee K (Oct 2021). Music Therapy in Sickle Cell Disease: Moving from Clinical Programs to Research. American Music Therapy Association National Conference, Virtual
19. **Rodgers-Melnick SN\****,* Block S\*, Dusek JA\* (Oct 2021). N=15,000: Large Scale Clinical Effectiveness Research in Medical Music Therapy. American Music Therapy Association National Conference, Virtual
20. **Rodgers-Melnick SN\***, DiScenna B, Bartolovich M, et al. (Oct 2021). Inpatient Integrative Therapies in Sickle Cell Disease: From Symptom Management to Self-Expression. Sickle Cell Disease Association of America Convention, Virtual
21. **Rodgers-Melnick SN\*** (Sep 2021). From Instrumentation to Innovation: Music Therapy in Comprehensive Cancer Care. 18th International Society for Integrative Oncology Conference, Baltimore, MD
22. **Rodgers-Melnick SN\***, Brill J, Block S, Rivard R, Dusek JA (Sep 2021) Effectiveness of Medical Music Therapy on Hematology/Oncology Patients at a Comprehensive Cancer Center. Society for Integrative Oncology Conference, Baltimore, MD
23. **Rodgers-Melnick SN\***, Brill J, Block S, Dusek JA (Sep 2021). Optimizing Technology to Deliver Virtual Music Therapy at a Comprehensive Cancer Center. Society for Integrative Oncology Conference, Baltimore, MD
24. **Rodgers-Melnick SN\*** (May 2021). Comfort Chorus. Duke University and University of North Carolina -- Comforting Our Community! Sickle Cell Together, Virtual
25. Brill J\**,* Block S\*, **Rodgers-Melnick SN\*** (Apr 2021). Overcoming Isolation During COVID-19: Integrating Music Therapy and Technology. Academic Consortium for Integrative Medicine and Health Symposium, Virtual
26. **Rodgers-Melnick SN\*** (Nov 2020). An Electronic Drum Circle for Patients, Family, and Staff at a Comprehensive Cancer Center. American Music Therapy Association National Conference, Virtual
27. **Rodgers-Melnick SN\***, Lin L, Gam K, et al. (Sep 2020). MUSic therapy to Improve Quality of Life in Sickle cell disease (MUSIQOLS): A Pilot Study Investigating Feasibility, Acceptability, and Preliminary Efficacy. 43rd National Sickle Cell Disease Scientific Meeting, Virtual
28. **Rodgers-Melnick SN\*** (Sep 2020). Music Therapy for Pain Management in Adults with Sickle Cell Disease. Berklee College of Music, Virtual
29. **Rodgers-Melnick SN\*** (Dec 2019). Music Therapy in Comprehensive Cancer Care. Case Western Reserve University School of Medicine, Cleveland, OH
30. **Rodgers-Melnick SN\*** (Oct 2019). Music Therapy in Comprehensive Cancer Care. Case Western Reserve University School of Medicine, Cleveland, OH
31. **Rodgers-Melnick SN\*** (Sep 2019). Music Therapy for Pain Management in Adults with Sickle Cell Disease. Sickle Cell Disease Educational Seminar: Integrative Medicine and Sickle Cell Disease: A Multi-Disciplinary 21st Century Approach, San Diego, CA
32. **Rodgers-Melnick SN\*** (Jul 2019). Music Therapy for Pain Management in Adults with Sickle Cell Disease. Academic Consortium for Integrative Medicine and Health, Virtual
33. **Rodgers-Melnick SN\*** (Mar 2019). Music Therapy in Comprehensive Cancer Care. Duquesne University, Mary Pappert School of Music, Pittsburgh, PA
34. **Rodgers-Melnick SN\*** (Feb 2019). Music Therapy for Adults with Sickle Cell Disease (Webinar). UH Elyria Medical Center, Elyria, OH
35. **Rodgers-Melnick SN\*** (Dec 2018). Music Therapy at UH Seidman Cancer Center. Case Western Reserve University School of Medicine, Cleveland, OH
36. **Rodgers-Melnick SN\*** (Nov 2018). Remix the Music for Pain: Music Use in Adults with Sickle Cell. American Music Therapy Association National Conference, Dallas, TX
37. **Rodgers-Melnick SN\***, Jenerette C, Matthie N, et al. (Oct 2018). Music Therapy Improves Pain Management in Adults with Sickle Cell Disease Treated at a Comprehensive Cancer Center. 15th Annual Conference of the Society for Integrative Oncology, Scottsdale, AZ
38. **Rodgers-Melnick SN\*** (Oct 2018). The BEATS Program: Sickle Cell Health Education Through Music Therapy. Sickle Cell Disease Association of America Convention, Baltimore, MD
39. **Rodgers-Melnick SN\*** (Jun 2018). Music Therapy in Sickle Cell Health Education. University Hospitals Cleveland Medical Center, Cleveland, OH
40. **Rodgers-Melnick SN\*** (May 2018). Music Therapy Research in Adults with Sickle Cell Disease. Case Comprehensive Cancer Center, Cleveland, OH
41. **Rodgers-Melnick SN\*** (Apr 2018). From MTI to PI: Conducting Research at an Academic Medical Cancer. Duquesne University, Mary Pappert School of Music, Pittsburgh, PA
42. **Rodgers-Melnick SN\*** (Nov 2017). Music Therapy Improves Pain Management in Adults with Sickle Cell Disease. American Music Therapy Association National Conference, St. Louis, MO
43. **Rodgers-Melnick SN\*** (Oct 2017). Music Therapy: Art and Science -- Rock and Roll. Cleveland Chapter of Oncology Nursing Society, Cleveland, OH
44. **Rodgers-Melnick SN\***, Jenerette C, Matthie N, et al. (Apr 2017). The Effects of a Single Music Therapy Session on the Pain of Adult Patients with Sickle Cell Disease: Results of a Mixed Methods Study. Foundation for Sickle Cell Disease Research Meeting, Fort Lauderdale, FL
45. **Rodgers-Melnick SN\*** (Nov 2016). From MTI to PI: Conducting Research in an Academic Medical Center. American Music Therapy Association National Conference, Sandusky, OH
46. **Rodgers-Melnick SN\***, Pell TJ, Lane D, Little J (Sep 2016). The Effects of Music Therapy on Transition Outcomes in Young Adult Patients with Sickle Cell Disease. Sickle Cell Disease Association of America Convention, Baltimore, MD
47. Lane D\**,* **Rodgers-Melnick SN\*** (Mar 2016). Music Therapy: Evidence & Efficacy. National Council of Jewish Women, Cleveland, OH
48. **Rodgers-Melnick SN\****,* Pell TJ\* (Sep 2015). Music Therapy in Sickle Cell Disease Management. Sickle Cell Disease Association of America Convention, Baltimore, MD
49. **Rodgers-Melnick SN\*** (Feb 2015). Music Therapy in Sickle Cell Disease Management. Duquesne University Chronic Pain Consortium, Pittsburgh, PA
50. **Rodgers-Melnick SN\****,* Block S\* (Nov 2014). The Seidman Studio: Applying Music Technology and Recording to Clinical Practice. American Music Therapy Association National Conference, Louisville, KY
51. Gutgsell KJ\**,* Pell TJ\*, **Rodgers-Melnick SN\*** (Mar 2014). Research-Based Music Therapy. 3rd Annual Palliative Care and Pain Symposium, Cleveland, OH

# Poster Presentations

1.  Srinivasan R, Segall TL\*, **Rodgers-Melnick SN**, Surdam J, Dusek JA (Dec 2023). Rationale for Integration of Patient Reported Outcomes in the Electronic Health Record: The SHARE Project. University Hospitals Research & Education Day, Cleveland, OH
2.  **Rodgers-Melnick SN\***, Srinivasan R, Rivard D, Adan F, Dusek JA (Dec 2023). Immediate Effects of Integrative Health and Medicine Modalities Among Outpatients with Moderate-to-Severe Pain, Stress, and Anxiety. University Hospitals Research & Education Day, Cleveland, OH
3.  **Rodgers-Melnick SN\***, Rivard RL, Block S, Dusek JA (Dec 2023). Clinical Effectiveness of Medical Music Therapy within Community Medical Centers: An EMMPIRE Retrospective Study. University Hospitals Research & Education Day, Cleveland, OH
4.  Srinivasan R, Segall TL, Rodgers-Melnick SN, Surdam J, Dusek JA (Sep 2023). Rationale for Integration of Patient Reported Outcomes in the Electronic Health Record: The SHARE Project. 2nd World Congress on Integrative Medicine and Health, Rome, IL
5.  **Rodgers-Melnick SN**, Bartolovich M\*, Desai NJ, et al. (Mar 2023). Massage Therapy for Children, Adolescents, and Young Adults (MATCHA): Clinical Delivery and Effectiveness in Hematology and Oncology. Case Comprehensive Cancer Center Disparities Symposium, Cleveland, OH
6.  **Rodgers-Melnick SN\***, Rivard RL, Block S, Dusek JA (Mar 2023). Clinical Effectiveness of Medical Music Therapy within Community Medical Centers: An EMMPIRE Retrospective Study. Integrative Medicine & Health Symposium, Chicago, IL
7.  Dusek JA, Kaiser C\*, Gannon T, Fitzgerald S, Adan F, **Rodgers-Melnick SN** (May 2022). Adjunctive Acupuncture within a Total Joint Replacement Program. International Congress on Integrative Medicine and Health, Phoenix, AZ
8.  **Rodgers-Melnick SN\***, Block S, Rivard RL, Dusek JA (May 2022) Optimizing Music Therapy Documentation in the Medical Setting: An EMMPIRE Process Improvement Study. International Congress on Integrative Medicine and Health, Phoenix, AZ
9.  **Rodgers-Melnick SN\***, Webb Hooper M (Mar 2020). Demographic and Clinical Predictors of Engaging in Tobacco Cessation Counseling at a Comprehensive Cancer Center. Case Comprehensive Cancer Center Cancer Disparities Symposium, Cleveland, OH
10. **Rodgers-Melnick SN\***, Webb Hooper M (Nov 2019). Predictors of Participation in Tobacco Cessation Counseling at a Comprehensive Cancer Center. Case Western Reserve University School of Medicine, Cleveland, OH
11. **Rodgers-Melnick SN\***, Jenerette C, Carvalho E, et al. (Oct 2019). MUSic therapy to Improve Quality of Life in Sickle cell disease: A Pilot Study. 16th Annual Conference of the Society for Integrative Oncology, New York, NY
12. **Rodgers-Melnick SN\***, Obermeier V, Gutgsell K, et al. (Oct 2019). Songs for the Journey Ahead: Music Therapy in Comprehensive Cancer Care. 16th Annual Conference of the Society for Integrative Oncology, New York, NY
13. **Rodgers-Melnick SN\***, Pell TJ, Lane D, et al. (Apr 2015). The Effects of a Single Music Therapy Session on the Pain of Adult Patients with Sickle Cell Disease: A Mixed Methods Study. The Foundation for Sickle Cell Disease Research Meeting, Hollywood, FL
14. **Rodgers-Melnick SN\***, Griest T, Lane D, et al. (Apr 2014). Music Therapy: A Feasible Approach to Symptom Management in Sickle Cell Disease. The Foundation for Sickle Cell Disease Research Meeting, Miami, FL
15. **Rodgers-Melnick SN\****,* Griest T\* (Nov 2013). Music Therapy in Sickle Cell Disease Management. American Music Therapy Association National Conference, Jacksonville, FL

# Podcasts

1.  Adan FA, Rodgers-Melnick SN, (Dec 2023). [Connecting the Mind and Body through Evidence-Based Integrative Modalities](https://www.uhhospitals.org/for-clinicians/articles-and-news/articles/2023/12/connecting-mind-body-through-evidence-based-integrative-modalities). Science\@UH Podcast
