---
title: "Publications"
---

# Peer Reviewed Articles

[PubMed Bibliography](https://www.ncbi.nlm.nih.gov/myncbi/samuel.rodgers-melnick.1/bibliography/public/)

1.  **Rodgers-Melnick SN**, Rivard RL, Block S, Dusek JA. Effectiveness of music therapy within community hospitals: an EMMPIRE retrospective study. PAIN Reports. 2023;8(3):e1074. doi:[10.1097/pr9.0000000000001074](http://doi.org/10.1097/pr9.0000000000001074)
2.  **Rodgers-Melnick SN**, Bartolovich M, Desai NJ, et al. Massage therapy for children, adolescents, and young adults: Clinical delivery and effectiveness in hematology and oncology. Pediatr Blood Cancer. Feb 1 2023;n/a(n/a):e30243. doi:[10.1002/pbc.30243](http://doi.org/10.1002/pbc.30243)
3.  **Rodgers-Melnick SN**, Rivard RL, Block S, Dusek JA. Clinical Delivery and Effectiveness of Music Therapy in Hematology and Oncology: An EMMPIRE Retrospective Study. Integr Cancer Ther. Jan-Dec 2022;21(21):15347354221142538. [doi:10.1177/15347354221142538](http://doi.org/10.1177/15347354221142538)
4.  **Rodgers-Melnick SN**, Lin L, Gam K, et al. Effects of Music Therapy on Quality of Life in Adults with Sickle Cell Disease (MUSIQOLS): A Mixed Methods Feasibility Study. J Pain Res. 2022;15:71-91. doi:[10.2147/JPR.S337390](http://doi.org/10.2147/JPR.S337390)
5.  **Rodgers-Melnick SN**, Zanotti K, Lee RT, Webb Hooper M. Demographic and Clinical Predictors of Engaging in Tobacco Cessation Counseling at a Comprehensive Cancer Center. JCO Oncol Pract. May 2022;18(5):OP.21.00458. doi:[10.1200/OP.21.00458](http://doi.org/10.1200/OP.21.00458)
6.  Jiang C, Larbi O, Feyes D, Wang G, Momotaz H, Li M, Daunov K, Daly B, Mazanec S, **Rodgers-Melnick SN**, et al. A survey of cancer patients, caregivers, and providers regarding familiarity, importance, and utilization of supportive and integrative oncology services. Support Care Cancer. Oct 2021;29(10):5777-5785. doi:[10.1007/s00520-021-06081-4](http://doi.org/10.1007/s00520-021-06081-4)
7.  **Rodgers-Melnick SN,** Gam K, Debanne S, Little JA. Music Use in Adult Patients with Sickle Cell Disease: A Pilot Survey Study. Music Ther Perspect. 2021;39(1):34-41. doi:[10.1093/mtp/miaa026](http://doi.org/10.1093/mtp/miaa026)
8.  Larbi OM, Jiang C, McLane B, Wang G, Daunov K, Hobson SM, Daly B, Mazanec SR, Feyes D, **Rodgers-Melnick SN**, et al. Interest and Willingness to Pay for Integrative Therapies of Patients With Cancer and Caregivers. JCO Oncol Pract. Nov 2021;17(11):OP.20.00471-OP.20.00471. doi:[10.1200/OP.20.00471](http://doi.org/10.1200/OP.20.00471)
9.  **Rodgers-Melnick SN**, Webb Hooper M. Implementation of tobacco cessation services at a comprehensive cancer center: a qualitative study of oncology providers' perceptions and practices. Support Care Cancer. May 2021;29(5):2465-2474. doi:[10.1007/s00520-020-05749-7](http://doi.org/10.1007/s00520-020-05749-7)
10. **Rodgers-Melnick SN**, Matthie N, Jenerette C, et al. The Effects of a Single Electronic Music Improvisation Session on the Pain of Adults with Sickle Cell Disease: A Mixed Methods Pilot Study. J Music Ther. Jun 7 2018;55(2):156-185. doi:[10.1093/jmt/thy004](http://doi.org/10.1093/jmt/thy004)
11. **Rodgers-Melnick SN**, Pell TJG, Lane D, et al. The effects of music therapy on transition outcomes in adolescents and young adults with sickle cell disease. Int J Adolesc Med Health. Aug 5 2017;31(3):1-14. doi:[10.1515/ijamh-2017-0004](http://doi.org/10.1515/ijamh-2017-0004)

# Peer Reviewed Articles -- In Press

1.  Shi Y, Nguyen K, Farrell M, Moss G, Kaiser C, **Rodgers-Melnick SN**, Mendiratta P, Dusek JA, Adan F, Lee RT. Implementation and Outcomes of a Pilot Acupuncture Program at a Comprehensive Cancer Center. In Press in Journal of Integrative and Complementary Medicine

# Peer Reviewed Articles -- Under Review

1.  **Rodgers-Melnick SN**, Rivard RL, Block S, Dusek JA. Effectiveness of Medical Music Therapy Practice: Integrative Research using the Electronic Health Record (EMMPIRE): Rationale, Design, and Population Characteristics. Submitted to Journal of Integrative and Complementary Medicine
2.  **Rodgers-Melnick SN**, Block S, Rivard RL, Dusek JA. Optimizing Patient-Reported Outcome Collection and Documentation in Medical Music Therapy: An EMMPIRE Process Improvement Study. Submitted to JMIR Human Factors. [Preprint available](https://preprints.jmir.org/preprint/46528)
3.  **Rodgers-Melnick SN**, Bradt J, Jenerette, C, Dusek JA. Music Therapy for Chronic Pain: Practical Recommendations for Future Research. Submitted to Journal of Music Therapy.

# Abstracts

1.  Jiang C, Larbi O, Feyes D, Momotaz H, Li M, Daunov K, Daly B, Mazanec S, **Rodgers-Melnick SN**, et al. Cancer Patients' and Healthcare Providers' Perceptions About Supportive and Integrative Oncology Services (S834). J Pain Symptom Manage. 2019;57(2):500-500. doi:[10.1016/j.jpainsymman.2018.12.287](http://doi.org/10.1016/j.jpainsymman.2018.12.287)

# Other works

1.  Rodgers-Melnick SN. [The Role of Music Therapy in Sickle Cell Disease](https://www.nbna.org//Files/NBNA%20Newsletters/cs_NBNA_SUMMER_2020%2010.28.pdf). Natl Black Nurses Assoc News. Published online August 2020:33-34.
